version: '3.2'

services:
  dgraph-zero:
    image: dgraph/dgraph:v1.1.0
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=dgraph-zero:5080
  dgraph-alpha:
    image: dgraph/dgraph:v1.1.0
    depends_on:
      - dgraph-zero
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    restart: always
    command: dgraph alpha --my=dgraph-alpha:7080 --lru_mb=2048 --zero=dgraph-zero:5080
  dgraph-ratel:
    image: dgraph/dgraph:v1.1.0
    depends_on:
      - dgraph-alpha
    volumes:
      - type: volume
        source: dgraph-data
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel

volumes:
  dgraph-data:
    driver: local
